version: '3'
services:
  stellar:
    image: stellar/quickstart
    container_name: stellar
    volumes:
      - ./stellar:/opt/stellar
    environment:
      - NETWORK=testnet
      - PGPASS=password
    ports:
      - '8000:8000'
      - '11625:11625'
      - '11626:11626'
    